language: pytho

python:
  - "3.6"
  - "3.7"
  - "3.8"      # current default Python on Travis CI
  - "3.9"
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install poetry
  - poetry build

before_script: 
  - pip install ell
  - pip install pytest

script:
  # :- "./.travis/run.sh"
  - pytest .travis/test.py
  - pytest tests/*.py

deploy:
  provider: releases
  file:
    - dist/*.whl
    - dist/*.tar.gz
  file_glob: true
  on:
    repo: Freakwill/ell
    tags: true
  skip_cleanup: true


